name: deploy-on-merge
on:
  pull_request:
    types: [closed]
permissions:
  contents: read
  deployments: write
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
jobs:
  deploy-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - run: npm ci --no-audit --no-fund
      - run: npx prisma generate || echo "no prisma"
      - run: npx vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
      - run: npx vercel build --prod --token="$VERCEL_TOKEN"
      - run: npx vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
